### ISSUE TITLE
Stylus Color Variables Are Not Found

### ISSUE THREAD

**Issue by andrewburgess** [abe33/atom-project-palette-finder#19]
It seems that the scanner doesn't pick up color variables for Stylus when prefixed with `$`.

```
red = #FF0000
```
will end up in the project palette, but
```
$red = #FF0000
```
will not end up in the project palette (though it does show up when using "find all colors")

This line (https://github.com/abe33/atom-project-palette-finder/blob/master/lib/project-palette-finder.coffee#L199) seems to cause the color to not get added.

**Comment by imperez** [comment]
I'm having the same issue. If I remove lines 199/200 from that fine above I my variables are highlighted though they aren't color coded in the autocomplete.

**Comment by abe33** [comment]
Oh right, I totally forgot that issue, sorry for the wait. I'll fix that soon.
