### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Provider' of null

### ISSUE THREAD

**Issue by Nicolab** [abe33/atom-project-palette-finder#21]
Uncaught TypeError: Cannot read property 'Provider' of null

**Atom Version**: 0.158.0
**System**: linux 3.13.0-43-generic
**Thrown From**: [project-palette-finder](https://github.com/abe33/atom-project-palette-finder) package, v2.4.6

### Stack Trace

```
At /home/nicolas/.atom/packages/project-palette-finder/lib/palette-provider.coffee:1

TypeError: Cannot read property 'Provider' of null
  at module.exports (/home/nicolas/.atom/packages/project-palette-finder/lib/palette-provider.coffee:1:20)
  at /home/nicolas/.atom/packages/project-palette-finder/lib/project-palette-finder.coffee:135:25

```

/cc @atom/core

**Comment by abe33** [comment]
I believe this issue can be closed. I'll reopen if needed.
