### ISSUE TITLE
Possible to ignore .atom folder

### ISSUE THREAD

**Issue by plttn** [abe33/atom-project-palette-finder#27]
At least i think it's project-palette-finder anyways, but when working in .atom folder, Atom gets extremely slow in that window. I'm assuming it's rebuilding all the colors for the entire .atom folder?

**Comment by abe33** [comment]
You can confirm that hypothesis by profiling Atom using the devtools and see where most of the time is consumed.

**Comment by plttn** [comment]
Yeah, just confirmed that.
