### ISSUE TITLE
UI sub-text difficult to read

### ISSUE THREAD

**Issue by dubert** [abe33/atom-project-palette-finder#39]
I'm not sure if this is an issue with Project Palette Finder, or my theme (I'm using Monokai for One Dark)
but this is what I see:

![screen shot 2015-04-17 at 13 23 20](https://cloud.githubusercontent.com/assets/1843672/7207121/2ad5c082-e505-11e4-9aee-b748a2b57c52.png)

I believe it's just a matter of a color not being set. It should use @text-color-subtle

**Comment by abe33** [comment]
Hi @dubert, sorry I completely missed your issue, BTW have you tried [pigments](http://atom.io/packages/pigments)? 
It's a rewrite of this package with `atom-color-highlight` and the palette view was improved.
I'm no longer maintain this package since pigments came out so I'll close that issue.

**Comment by felixakiragreen** [comment]
Thanks! I'll switch to it! Atom needs a better way to let people know things like this.
